redis-master:
  image: redis:3.2.11
redis-slave:
  image: redis:3.2.11
  command: redis-server --slaveof redis-master 6379
  links:
    - redis-master:redis-master
redis-sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
    - SENTINEL_QUORUM=2
  links:
    - redis-master:redis-master
    - redis-slave
  command: redis-server /etc/redis/sentinel.conf --sentinel